baseURL = "https://egeretto.h4ck.me/"
languageCode = "en-us"
title = "MissingFantasy<wbr>Exception"
theme = "hugo_theme_pickles"
pygmentsStyle = "manni"

[params]
  subtitle = "Yet another oddly-titled IT security blog"
  favicon = "/images/favicon.png"

  author = "Elia Geretto"
  avatar = "/images/profile.jpg"
  bio = "IT Security Enthusiast - CTF Player - CS Master Student"

  github = "EliaGeretto"
  twitter = "EliaGeretto"
  facebook = "EliaGeretto"
