baseURL = "https://aliverix.homepc.it/"
languageCode = "en-us"
title = "MissingFantasy<wbr>Exception"
theme = "hugo_theme_pickles"

[params]
  subtitle = "Yet another oddly-titled IT security blog"
  author = "Elia Geretto"
  avatar = "/images/profile.jpg"
  bio = "Security Enthusiast - CTF Player - CS Master Student"

  github = "EliaGeretto"
  twitter = "EliaGeretto"
  facebook = "EliaGeretto"
