baseURL = "https://aliverix.homepc.it/"
languageCode = "en-us"
title = "MissingFantasyException"
theme = "hugo_theme_pickles"

[params]
  github = "EliaGeretto"
  twitter = "EliaGeretto"
  facebook = "EliaGeretto"
